### ISSUE TITLE
Profile tool exception

### ISSUE THREAD

**Issue by max-trolliet** [QGEP/qgepplugin#17]
```
TypeError: 'OutEdgeDataView' object is not subscriptable 
Traceback (most recent call last):
  File "C:/Users/mtt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptools.py", line 129, in canvasReleaseEvent
    self.leftClicked(event)
  File "C:/Users/mtt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptools.py", line 426, in leftClicked
    pf = self.findPath(self.selectedPathPoints[-1][0], match.featureId())
  File "C:/Users/mtt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptools.py", line 295, in findPath
    self.appendProfile(vertices, edges)
  File "C:/Users/mtt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptools.py", line 322, in appendProfile
    edge_ids = [edge['feature'] for p1, p2, edge in edges]
  File "C:/Users/mtt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptools.py", line 322, in 
    edge_ids = [edge['feature'] for p1, p2, edge in edges]
TypeError: 'OutEdgeDataView' object is not subscriptable
```

**Comment by m-kuhn** [comment]
2.0

**Comment by schoeller** [comment]
I ran into a similar issue. I did the following as administrator user from the OSGeo4W command line

<code>pip uninstall networkx decorator</code>
<code>pip install networkx==1.11 --force-reinstall</code>

It did not work. I am running Qgis3.2.1.

**Comment by schoeller** [comment]
Manually comparing networkx package version infos between
`c:\Program Files\QGIS 3.2\apps\Python36\Lib\site-packages\`
and 
`c:\Program Files\QGIS 3.2\apps\Python27\Lib\site-packages\`
I noticed that they had different versions installed. Python 3.6 had networkx version 2.x installed. After manually deleting the package directories for networkx 2.x packages I executed 
`py3_env`
on the OSGeo4W command line to alter the environment to Python 3. I then installed networkx 1.11
`pip install -U networkx==1.11 --force-reinstall`
Now the error has changed to
```
File "C:/Users/sschoeller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptools.py", line 322, in 
    edge_ids = [edge['feature'] for p1, p2, edge in edges]
TypeError: list indices must be integers or slices, not str
```

**Comment by sjib** [comment]
See https://github.com/QGEP/qgepplugin/issues/23 - may be that helps

**Comment by schoeller** [comment]
Using Qgis 3.4.1 on Windows 10 with networkx 2.2 installed and qgepplugin from master dated Nov 2, 2018 I can confirm that profile detection works as well as up- and downstream detection. Profiles are not plotted as on my Linux installation.

![image](https://user-images.githubusercontent.com/106036/48138568-817c9080-e29c-11e8-91be-53c010de735d.png)

**Comment by m-kuhn** [comment]
Thanks for the feedback.
Are the profiles plotted on windows?

**Comment by schoeller** [comment]
No. Please see screenshot above. I have installed the following additional packages using

`pip install numpy scipy matplotlib graphviz pyparsing pyyaml`

Presuming that graphical output might be generated through graphviz/matplotlib.

**Comment by m-kuhn** [comment]
It's generated through QtWebKit is there anything available related to this?

**Comment by schoeller** [comment]
There is no further stacktrace message so I cannot tell. I presume Qt should be loaded either through the installation directory or through system PATHS defined. I do not know unfortunately. The install was fresh.

**Comment by schoeller** [comment]
I retried behaviour on a Linux installation using 3.4.1. Same as on Windows after installing qgepplugin master the profile tracing is working as is up-, downstream. The profile is plotted too, but the plot uses roughly 1/4 of the existing space. 

![grafik](https://user-images.githubusercontent.com/106036/48159981-04224180-e2d7-11e8-98d4-585cc4adfb60.png)

**Comment by schoeller** [comment]
Tested on Windows10 with Qgis 3.4.2 I receive no profile as per comment https://github.com/QGEP/qgepplugin/issues/17?_pjax=%23js-repo-pjax-container#issuecomment-436648641 above.

**Comment by m-kuhn** [comment]
Can you try again with release 1.1.6?

**Comment by schoeller** [comment]
Uninstalled 1.1.6 and reinstalled through ZIP on Win10 using Qgis 3.4.2. Resulting profile is empty.
![image](https://user-images.githubusercontent.com/106036/49741516-8020f800-fc8e-11e8-8dd0-296d8e84ac13.png)

**Comment by m-kuhn** [comment]
If you go to qgep settings -> debugging and activate debugging, are you able to right click on the white space and choose "inspect"?

**Comment by m-kuhn** [comment]
In the comment https://github.com/QGEP/qgepplugin/issues/17#issuecomment-436774062 you had some partial success, what's the difference to now?

**Comment by schoeller** [comment]
Partial success was on Ubuntu. On Windows I haven't so far. Inspector give below screenshot.
![image](https://user-images.githubusercontent.com/106036/49744547-eb6dc880-fc94-11e8-9d4d-92c7cb1c9a33.png)

**Comment by schoeller** [comment]
When testing with version 1.1.6 on Ubuntu Qgis 3.4.2 the profile is shown as expected, thus an improvement.
![grafik](https://user-images.githubusercontent.com/106036/49756855-3f8ba380-fcbb-11e8-9607-4f0ab0f918dc.png)
Win10 install is not working. I will have to find a fresh Win10 install in order to verify.

**Comment by m-kuhn** [comment]
Most likely the same issue as this one reported today:
http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-QGIS-3-4-QWebView-Problem-loading-a-website-with-javascript-files-td5388759.html

**Comment by schoeller** [comment]
Works, thank you!
