### ISSUE TITLE
QGEP Plugin 1.1.2 crashes at installation - networkx missing

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepplugin#23]
Konnte Erweiterung 'qgepplugin' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

ModuleNotFoundError: No module named 'networkx' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\__init__.py", line 27, in classFactory
    from .qgepplugin import QgepPlugin
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepplugin.py", line 41, in 
    from .tools.qgepmaptools import (
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptools.py", line 59, in 
    from .qgepnetwork import QgepGraphManager
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepnetwork.py", line 50, in 
    import networkx as nx
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'networkx'

Python-Version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS-Version: 3.3.0-Master Master, 1192f949ec 

Python-Pfad:
C:/OSGEO4~1/apps/qgis-dev/./python
C:/Users/stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis-dev/./python/plugins
C:\OSGeo4W64\bin\python36.zip
C:\OSGEO4~1\apps\Python36\DLLs
C:\OSGEO4~1\apps\Python36\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python36
C:\OSGEO4~1\apps\Python36\lib\site-packages
C:/Users/stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Daten/QGEP/Arbon

**Comment by sjib** [comment]
Workaround - install **networkx** and **setuptools** for Python3 manually via OSGeo4W install

**Comment by sjib** [comment]
![networkx_qgis3_skipped](https://user-images.githubusercontent.com/1265865/44735297-56333380-aaec-11e8-8928-70932e743c5a.jpg)
Change from skipped to selected

**Comment by sjib** [comment]
@3nids Please update plugin so that it checks itself if libraries are installed.

**Comment by sjib** [comment]
Should be solved with https://github.com/QGEP/qgepplugin/releases 1.15. Else please reopen
