### ISSUE TITLE
Error on qgepplugin at qgis start

### ISSUE THREAD

**Issue by ponceta** [QGEP/qgepplugin#3]
Une erreur est survenue lors de l'éxécution du code Python:
```
UnboundLocalError: local variable 'vertex' referenced before assignment
Traceback (most recent call last):
  File "C:/Users/pulpoar/.qgis2/python/plugins\qgepplugin\qgepplugin.py", line 254, in onLayersAvailable
    self.network_analyzer.setNodeLayer(layers['vw_network_node'])
  File "C:/Users/pulpoar/.qgis2/python/plugins\qgepplugin\tools\qgepnetwork.py", line 107, in setNodeLayer
    self.createGraph()
  File "C:/Users/pulpoar/.qgis2/python/plugins\qgepplugin\tools\qgepnetwork.py", line 229, in createGraph
    self._addVertices()
  File "C:/Users/pulpoar/.qgis2/python/plugins\qgepplugin\tools\qgepnetwork.py", line 129, in _addVertices
    self.graph.add_node(fid, dict(point=vertex, objType=obj_type))
UnboundLocalError: local variable 'vertex' referenced before assignment
```

Version de Python : 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
Version de QGIS : 2.18.7 Las Palmas, 3b30e6a
```
Chemin Python :
C:/Users/pulpoar/.qgis2/python/plugins\processing
C:/OSGEO4~1/apps/qgis/./python
C:/Users/pulpoar/.qgis2/python
C:/Users/pulpoar/.qgis2/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\apps\qgis\python
C:\Users\pulpoar\.qgis2\python
C:\OSGEO4~1\bin\python27.zip
C:\OSGEO4~1\apps\Python27\DLLs
C:\OSGEO4~1\apps\Python27\lib
C:\OSGEO4~1\apps\Python27\lib\plat-win
C:\OSGEO4~1\apps\Python27\lib\lib-tk
C:\OSGEO4~1\bin
C:\OSGEO4~1\apps\Python27
c:\osgeo4~1\apps\python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
c:\osgeo4~1\apps\python27\lib\site-packages\shapely-1.2.18-py2.7-win-amd64.egg
c:\osgeo4~1\apps\python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python27\lib\site-packages\Pythonwin
C:\OSGEO4~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:/Users/pulpoar/.qgis2//python
C:/Temp/QGIS_Project_Pully_QGEP
```

**Comment by m-kuhn** [comment]
can you 

    REFRESH MATERIALIZED VIEW qgep.vw_network_segment;
    REFRESH MATERIALIZED VIEW qgep.vw_network_node;

and restart QGIS?

**Comment by ponceta** [comment]
Query returned successfully with no result in 4.4 secs.

QGIS restarted. Problem still here.

**Comment by ponceta** [comment]
I get this python error at every QGEP loading. Maybe a remote session could be great to identify the problem?

**Comment by ponceta** [comment]
This has been fixed.
