### ISSUE TITLE
Plugin raises error with null geometries

### ISSUE THREAD

**Issue by haubourg** [QGEP/qgepplugin#33]
Hi, I'm testing plugin 1.1.8 with latest DB version `1.1.1 fix_depth_after_node_update` and I get an error using the demo dataset, in qgis master 3.5

```
WARNING    Traceback (most recent call last):
              File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/qgepplugin.py", line 282, in onLayersAvailable
              self.network_analyzer.setNodeLayer(layers['vw_network_node'])
              File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepnetwork.py", line 107, in setNodeLayer
              self.createGraph()
              File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepnetwork.py", line 225, in createGraph
              self._addVertices()
              File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepnetwork.py", line 125, in _addVertices
              vertex = feat.geometry().asPoint()
             ValueError: Null geometry cannot be converted to a point.
```

I ran a  `select * from qgep_od.vw_network_node where detail_geometry is null` and found indeed three rows with a null geometry. 
Then I deleted them from `reach_point` and `wastewater_node` and refreshed materialized views afterward. 

The stack error about NULL geometries disappeared but then I encounter that strange error:

```
TypeError: 'method' object is not subscriptable 
Traceback (most recent call last):
  File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepmaptools.py", line 129, in canvasReleaseEvent
    self.leftClicked(event)
  File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepmaptools.py", line 426, in leftClicked
    pf = self.findPath(self.selectedPathPoints[-1][0], match.featureId())
  File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepmaptools.py", line 294, in findPath
    (vertices, edges) = self.network_analyzer.shortestPath(start_point, end_point)
  File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepnetwork.py", line 269, in shortestPath
    edges = [(u, v, self.graph.edges[u, v]) for (u, v) in zip(path[0:], path[1:])]
  File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepnetwork.py", line 269, in 
    edges = [(u, v, self.graph.edges[u, v]) for (u, v) in zip(path[0:], path[1:])]
TypeError: 'method' object is not subscriptable

````
Did I miss something? Anyone is having the profile tool working?

**Comment by m-kuhn** [comment]
Concerning error 1, I wonder if we should set a NOT NULL constraint on the network node detail_geometry column (@urskaufmann do you see a reason to have network nodes without a geometry?)

Concerning point 2, this line was adjusted in a commit https://github.com/QGEP/qgepplugin/commit/914956a00cf33231b7c5a02f745fa629dc4de98c - what's the networkx version you have installed?

**Comment by haubourg** [comment]
> Concerning point 2, this line was adjusted in a commit [914956a](https://github.com/QGEP/qgepplugin/commit/914956a00cf33231b7c5a02f745fa629dc4de98c) - what's the networkx version you have installed?

This is 1.11-1 from ubuntu repositories on ubuntu 18.04. 

I never manage to catch paths and sometimes face errors like this one:
````

TypeError: 'method' object is not subscriptable 
Traceback (most recent call last):
  File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepmaptools.py", line 129, in canvasReleaseEvent
    self.leftClicked(event)
  File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepmaptools.py", line 426, in leftClicked
    pf = self.findPath(self.selectedPathPoints[-1][0], match.featureId())
  File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepmaptools.py", line 294, in findPath
    (vertices, edges) = self.network_analyzer.shortestPath(start_point, end_point)
  File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepnetwork.py", line 269, in shortestPath
    edges = [(u, v, self.graph.edges[u, v]) for (u, v) in zip(path[0:], path[1:])]
  File "/home/regis/.local/share/QGIS/QGIS3/profiles/test/python/plugins/qgepplugin/tools/qgepnetwork.py", line 269, in 
    edges = [(u, v, self.graph.edges[u, v]) for (u, v) in zip(path[0:], path[1:])]
TypeError: 'method' object is not subscriptable
````

**Comment by m-kuhn** [comment]
You need to have Version 2.x installed

**Comment by haubourg** [comment]
@m-kuhn thanks! I couldn't find any requirement in the doc or the readme, did I miss them ?

**Comment by m-kuhn** [comment]
I've been [reworking version requirements](https://github.com/QGEP/docs/pull/64/files#diff-1e80e5b9d1ae00612316014fa4a38504) recently, I just added that. Thanks.

**Comment by urskaufmann** [comment]
_do you see a reason to have network nodes without a geometry?_
No, there is no reason. If you think about the hydraulic software, that should make calculations with this networknodes - at least then you will get an error because of the missing geometry.
Some people propably say, if there is no geometry, then take the geometry of the cover of this wastewater structure ...
